rails-base-master/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"
  resources :users, only: [:new, :create]
  resources :comments, only: [:new, :create, :show]
  resources :home, only: :index
  resources :tags, only: :index
  resources :posts, only: [:index, :show, :new, :create]
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'tags/', to: 'tags#index'
end

rails-base-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

rails-base-master/app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comments, foreign_key: :parent_comment_id
  validates :body, presence: true
end

rails-base-master/app/models/post.rb
class Post < ApplicationRecord

  has_many :taggings
  has_many :comments, foreign_key: :parent_comment_id
  has_many :tags, through: :taggings
  validates :title, :content, :autor, presence: true
  paginates_per 10
  scope :search_by_title, -> search_params {where("lower(title) like ?","%#{search_params.downcase}%")} 

  def self.tagged_with(id)
    Tag.find_by!(id: id.to_i).posts
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

end

rails-base-master/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings
  paginates_per 30
  scope :filter_tags, -> tags_ids {where(id: tags_ids.split(', '))}



end

rails-base-master/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post

end

rails-base-master/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password

end

rails-base-master/app/controllers/admin/base_controller.rb
class Admin::BaseController < BaseController
end

rails-base-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  protect_from_forgery with: :exception

  protected
  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Necessário efetuar o login."
    end
  end
end

rails-base-master/app/controllers/base_controller.rb
class BaseController < ApplicationController
end

rails-base-master/app/controllers/comments_controller.rb
class CommentsController < BaseController
  skip_before_action :authorize
  before_action :set_comment, only: :show
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if session[:user_id].nil?
      @comment.author = 'Anonymous'
    else
      @comment.author = User.find(session[:user_id]).name
    end

    respond_to do |format|
      if @comment.save
        format.html{ redirect_back fallback_location: root_path, notice: 'Comentário realizado.' }
        format.js
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :author, :parent_comment_id)

  end
end

rails-base-master/app/controllers/home_controller.rb
class HomeController < BaseController
  skip_before_action :authorize
  def index
    @posts = Post.all.sort{|a,b| b <=> a}.take(5)
  end
end

rails-base-master/app/controllers/posts_controller.rb
class PostsController <ApplicationController
  skip_before_action :authorize, only: [:show, :index]
  before_action :set_post, only: [:show, :create]
  has_scope :search_by_title
  has_scope :filter_tags
  def index

    @all_posts = Post.all.order(created_at: :desc)
    if params[:search].present?
      @all_posts = @all_posts.search_by_title(params[:search]).all.page(params[:page])
    end
    if params[:tags_ids].present?
      parameters = params[:tags_ids].split(', ').uniq
      @tags_searched = Tag.filter_tags(params[:tags_ids])
      @all_posts = @all_posts.joins(:taggings)
      .where(taggings: { tag_id: parameters })
      .group(:id)
      .having("count(posts.id) = #{parameters.count}")
    end
    @all_posts = @all_posts.page(params[:page])
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post criado com sucesso.'
    else
      render :new
    end
  end

  private

  def set_post
    if params[:id]
      @post = Post.find(params[:id])
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :autor, :tag_list)
  end
end

rails-base-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new
  end
  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_url, notice: "#{(user.name).upcase} logado com sucesso"
    else
      redirect_to login_url, alert: "Usuário/Senha incorretos"
    end

  end
  def destroy
    session[:user_id] = nil
    redirect_to home_index_url, notice: "Usuário saiu!"
  end

end

rails-base-master/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_action :authorize
  before_action :set_tag, only: [:index, :show]
  def index
    @description = "Utilize esta tag quando a pergunta se refere a alguma informação ou problema relacionado exclusivamente à"
    if params[:name]
      @tag = Tag.where("lower(name) like ?","%#{params[:name].downcase}%").order(:name).page params[:page]
    else
      @tag = Tag.all.order(:name).page params[:page]
    end
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to @tag, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  private

  def set_tag
    if params[:id]
      @tag = Tag.find(params[:id])
    else
      @tag = Tag.all.order(:name)
    end
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

rails-base-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_url, notice: "Usuário #{@user.name} criado com sucesso!"
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

rails-base-master/app/helpers/application_helper.rb
module ApplicationHelper
  
end

rails-base-master/app/helpers/comments_helper.rb
module CommentsHelper
  def calculate_time_ago(created_at_comment)
    time_now = Time.now
    time_now.day - created_at_comment.day
  end
end

rails-base-master/app/helpers/posts_helper.rb
module PostsHelper
  def calculate_time_ago(created_at_post)
    time_now = Time.now
    time_now.day - created_at_post.day
  end
end

rails-base-master/app/helpers/tags_helper.rb
module TagsHelper

end

rails-base-master/app/views/comments/_comment.html.erb
<div class="col-md-2">
  <div class="thumbnail">
    <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
  </div>
</div>
<li class="col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <% if TimeDifference.between(comment.created_at, Time.now).in_hours.round == 0 %>
      <strong><%= comment.author %></strong> <span class="text-muted pull-right">Há <%= TimeDifference.between(comment.created_at, Time.now).in_minutes.round %> minutos</span>
      <% else %>
      <strong><%= comment.author %></strong> <span class="text-muted pull-right">Há <%= TimeDifference.between(comment.created_at, Time.now).in_hours.round %> horas</span>
      <% end %>
    </div>
    <div class="panel-body">
      <%= comment.body %>
    </div>
  </div>
  <%= render partial: 'comments/form', locals: { parent_id: comment.id } %>
  <br>
  <ul>
    <li>
      <%= render partial: 'comments/comment',collection: comment.comments%>
    </li>
  </ul>
</li>

rails-base-master/app/views/comments/_form.html.erb
<% parent_id = parent_id || nil %>
<%= form_for(:comment, url: comments_path, remote: true) do |form| %>
<div class="row form">
  <div class="col-md-8">
    <form class="text-center">
      <div class="form-group">
        <%= form.text_area :body,placeholder: "Conteúdo", rows: 4,class: "form-control body" %>
      </div>
        <%= form.hidden_field :parent_comment_id, value: parent_id %>

      <div>
        <%= form.submit 'Comentar',value:"Comentar", class: "btn btn-info"%>
      </div>
    </form>
  </div>
</div>
<% end %>

rails-base-master/app/views/comments/create.js.erb
$('#comments').html("<%= j(render partial: 'comments/comment', collection: @post.comments)%>");

rails-base-master/app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>

rails-base-master/app/views/home/index.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class=""></li>
		<li data-target="#myCarousel" data-slide-to="1" class=""></li>
		<li data-target="#myCarousel" data-slide-to="2" class="active"></li>
	</ol>
	<div class="carousel-inner" role="listbox">
		<div class="item">
			<%= image_tag("tec.jpeg", class: "first-slide slide-image") %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Tecnologia</h1>
					<p>Fique por dentro do mundo da tecnologia.</p>
				</div>
			</div>
		</div>
		<div class="item">
			<%= image_tag("news.jpeg", class: "second-slide slide-image") %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Notícias</h1>
					<p>Compartilhe ideias e acontecimentos.</p>
				</div>
			</div>
		</div>
		<div class="item active">
			<%= image_tag("social_media.jpeg", class: "third-slide slide-image") %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Redes sociais</h1>
					<p>Não perca o que está bombando no momento.</p>
				</div>
			</div>
		</div>
	</div>
	<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		<span aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		<span aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>
<div class="container-fluid main">
	<%if notice %>
		<p id="notice" class="alert alert-danger">
			<%= notice %>
		</p>
	<% end %>
	<div class="row search-bar">
		<div class="form-group col-md-4 ">
			<%= form_tag(posts_path, method: :get) do %>
			<div class="col-md-8 pull-left">
				<%= text_field_tag 'search', nil, placeholder: 'Digite o título do post...', class: "form-control " %>
			</div>
			<div class = "pull-left">
				<%= button_tag fa_icon(:search), class: "btn btn-default"%>
			</div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="new col-md-3 pull-right">
			<a ><%= link_to fa_icon(:plus), new_post_path, class: "btn btn-success"  %></a>
		</div>
	</div>
	<% @posts.each do |post| %>
	<div class="col-md-12 ">
		<div class="panel text-justify panel-post">
			<div class="panel-body ">
				<h3 class="panel-title"><%= post.title %></h3>
				<p class="panel-text content"><%= post.content.truncate(100) %></p>
				<span>
					<%= raw post.tags.map { |tag| link_to tag.name.to_s, posts_path(tags_ids: [params[:tags_ids], tag.id].reject(&:blank?).compact.join(', '), search: params[:search]), class: " label label-info tag-label" }.join(' ') %>
				</span>
				<p class="panel-text autor">Postado por <%= post.autor %></p>
				<% if TimeDifference.between(post.created_at, Time.now).in_days.round == 0 %>
				  <p class="panel-text autor">Postado hoje</p>
				<% else %>
					<p class="panel-text autor"><%= TimeDifference.between(post.created_at, Time.now).in_days.round%> dia(s) atrás</p>
				<% end %>
				<a><%= link_to 'Leia mais', post %></a>
			</div>
		</div>
	</div>
	<% end %>
	<div class="row">
		<div class="col-md-4">
			<a><%= link_to 'Ver todos >>', posts_url, class: "text-center" %></a>
		</div>
	</div>

rails-base-master/app/views/layouts/application.slim
<!DOCTYPE html>
<html>
head
  title Rails Treinamento
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
body
  .row
    .navbar.navbar-default.navbar-fixed-top.header
      .container-fluid
        .navbar-header
          a.navbar-brand
            = link_to 'Codditus', home_index_path,  class: "brand d-inline-block align-center"
        -if session[:user_id].nil?
          a
            = link_to fa_icon('user-plus', text: 'Sign up'), new_user_path,  class: "btn btn-success btn-lg text-uppercase nav-link pull-right btn-up"
          a
            = link_to fa_icon('sign-in', text: 'Sign in'), login_url,  class: " btn btn-primary btn-lg text-uppercase nav-link pull-right btn-in"
        -else
          a
          = link_to fa_icon('sign-out', text: 'Sign out'), sessions_destroy_path,  class: "btn btn-danger btn-lg text-uppercase nav-link pull-right btn-out"
  = yield

rails-base-master/app/views/posts/_form.slim
= simple_form_for @post, defaults: { input_html: { class: 'form-control' } } do |form|
  .container
    .row.form
      .col-md-12
        form.text-center
        -if @post.errors.any?
          .alert.alert-danger
            =form.error_notification
        .form-group
          = form.input :title,label: 'Titulo', placeholder: "Título", error: 'Preencha o título'
        .form-group
          = form.input :content,label: 'Conteúdo', placeholder: "Conteúdo", input_html: {rows: 20},error: 'Preencha o conteúdo'
        .field
          = form.input :tag_list,label: 'Tags',hint: '(Separadas por vígula)', placeholder: "Tags"
        .form-group
          = form.hidden_field :autor, value: User.find(session[:user_id]).name
        .form-group
          = form.button :submit, 'Criar post',value:"Criar post", class: "btn btn-info"

rails-base-master/app/views/posts/index.html.erb
<div class="container-fluid main main-posts">
  <br>
  <%if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
  <% end %>
  <div class="row search-bar">
    <div class="form-group col-md-4 ">
      <%= form_tag(posts_path, method: :get) do %>
      <%= hidden_field_tag :tags_ids, params[:tags_ids] %>
      <div class="col-md-8 pull-left">
        <%= text_field_tag 'search', params[:search], placeholder: 'Digite o título do post...', class: "form-control " %>
      </div>
      <div class = "pull-left">
        <%= button_tag fa_icon(:search), value: "search_title", class: "btn btn-default"%>
      </div>
      <% end %>
    </div>
  </div>
  <div class="">
    <% if params[:tags_ids].present? %>
    <% @tags_searched.each do |tag|  %>
    <span >
      <%= link_to tag.name, posts_path(tags_ids: [params[:tags_ids].split(', ') - [tag.id.to_s]].compact.join(', ') , search: params[:search]), class: " label label-info tag-label"%>
      <span>
        <%= link_to fa_icon(:times), posts_path(tags_ids: [params[:tags_ids].split(', ') - [tag.id.to_s]].compact.join(', ') , search: params[:search])%>
      </span>
    </span>
    <% end %>
    <% end %>
  </div>
  <div class="row">
    <div class="new col-md-3 pull-right">
      <a ><%= link_to fa_icon(:plus), new_post_path,id: "new-home", class: "btn btn-success"  %></a>
    </div>
  </div>
  <br>
  <div class="row clearfix">
    <div class="col-md-3 nav-aside text-center">
      <div class="panel">
        <div class="panel-header">
          <h4>Popular Tags</h4>
        </div>
        <ul class="list-group text-left">
          <% Tag.take(8).each do |tag| %>
          <li class="list-group-item">
            <span >
              <%= link_to tag.name.to_s, posts_path(tags_ids: [params[:tags_ids], tag.id].reject(&:blank?).compact.join(', '), search: params[:search]), class: " label label-info tag-label"%>
            </span>
          </li>
          <% end %>
          <li class="list-group-item">
            <a><%= link_to 'Ver mais tags >>', tags_url, class: "text-center" %></a>
          </li>
        </ul>
      </div>
    </div>
    <% if @all_posts.empty? %>
    <div class="col-md-8">
      <hr>
      <h1>Não existe nenhum post!</h1>
    </div>
    <% else %>
    <% @all_posts.each do |post| %>
    <div class="col-md-8">
      <div class="panel text-justify panel-post">
        <div class="panel-body ">
          <h3 class="panel-title"><%= post.title %></h3>
          <p class="panel-text content"><%= post.content.truncate(100) %></p>
          <span>
            <%= raw post.tags.map { |tag| link_to tag.name.to_s, posts_path(tags_ids: [params[:tags_ids], tag.id].reject(&:blank?).compact.join(', '), search: params[:search]), class: " label label-info tag-label" }.join(' ') %>
          </span>
          <p class="panel-text autor">Postado por <%= post.autor %></p>
          <% if TimeDifference.between(post.created_at, Time.now).in_days.round == 0 %>
            <p class="panel-text autor">Postado hoje</p>
          <% else %>
            <p class="panel-text autor"><%= TimeDifference.between(post.created_at, Time.now).in_days.round%> dia(s) atrás</p>
          <% end %>
          <a><%= link_to 'Leia mais', post %></a>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
  <nav>
    <%= paginate @all_posts,  outer_window: 3, class: "pagination" %>
  </nav>
</div>

rails-base-master/app/views/posts/new.html.erb
<%= render 'form', post: @post %>

rails-base-master/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
  <div class="container-fluid main main-posts">
    <div class="row text-center">
      <div class="col-md-2">
      </div>
      <div class="col-md-10 post text-justify">
        <div class="">
          <h2 class="post-title"><%= @post.title %></h2>
        </div>
        <hr>
        <div >
          <p class="post-autor"> <%= @post.autor %></p>
        </div>
        <div >
          <% if TimeDifference.between(@post.created_at, Time.now).in_days.round == 0 %>
          <p class="panel-text autor">Postado hoje</p>
          <% else %>
          <p class="panel-text autor"><%= TimeDifference.between(@post.created_at, Time.now).in_days.round%> dia(s) atrás</p>
          <% end %>
        </div>
        <hr>
        <div class="col-md-8">
          <div >
            <p class=""><%= simple_format(h(@post.content), class: "post-body") %></p>
          </div>
          <span>
            <%= raw @post.tags.map { |tag| link_to tag.name, tag_path(tag), class: "label label-info tag-label" }.join(' ') %>
          </span>
        </div>
        <div class="col-md-10">
        </div>
        <div class="col-md-6">
          <%= form_for(:comment, url: comments_path, remote: true) do |form| %>
          <div class="row form">
            <div class="col-md-10">
              <form class="text-center">
                <h2>Deixe um comentário<span><%= fa_icon(:comments) %></span></h2>
                <div class="form-group">
                  <%= form.text_area :body,placeholder: "Conteúdo" , rows: 5, class: "form-control" %>
                </div>
                <%= form.hidden_field :parent_comment_id, value: @post.id %>
                <div>
                  <%= form.submit 'Comentar',value:"Comentar", class: "btn btn-info" %>
                </div>
              </form>
            </div>
          </div>
          <% end %>
          <br>
          <div class="row">
            <div class="col-md-12">
              <h2>Comentários<span class="text-muted pull-right"><%= pluralize(@post.comments.count, "Comentário") %></span></h2>
            </div>
          </div>
          <ul id="comments">
            <%= render partial: 'comments/comment', collection:  @post.comments %>
          </ul>
        </div>
      </div>
      <hr>
    </div>
  </div>

rails-base-master/app/views/tags/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="row search-bar">
      <div class="form-group col-md-4 ">
        <%= form_tag(tags_path, method: :get) do %>
        <div class="col-md-8 pull-left">
          <%= text_field_tag 'name', nil, placeholder: 'Proucure por uma tag...', class: "form-control " %>
        </div>
        <div class = "pull-left">
          <%= button_tag fa_icon(:search), class: "btn btn-default"%>
        </div>
        <% end %>
      </div>
    </div>
    <div class="tags">
      <% @tag.each do |tag| %>
      <div class="panel panel-default tag col-md-2 pull-left">
        <span >
          <%= link_to tag.name, posts_path(tags_ids: [params[:tags_ids], tag.id].compact.join(', '), search: params[:search]), class: " label label-info tag-label"%>
        </span>
        <p class="panel-body"><%="#{@description.truncate(80)}"%></p>
      </div>
      <% end %>
    </div>
  </div>

  <nav>
    <%= paginate @tag,  outer_window: 3, class: "pagination" %>
  </nav>
</div>

rails-base-master/app/views/users/_form.html.erb
<%= form_for(@user) do |form| %>
<div class="form">
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li class="alert alert-danger"><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="card card-container">
    <img id="profile-img" class="profile-img-card" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" />
    <p id="profile-name" class="profile-name-card"></p>
    <form class="form-signin">
      <span id="reauth-email" class="reauth-email"></span>
      <%= form.text_field :name,placeholder: "Nome...", class: "form-control input inputField " %>
      <br>
      <%= form.password_field :password,placeholder: "Senha...", class: "form-control input inputField" %>
      <br>
      <%= form.password_field :password_confirmation,placeholder: "Confirme a senha...", class: "form-control input inputPassword" %>
      <br>
      <%= form.submit 'Cadastrar-se',value:'Cadastrar-se', class: "btn btn-success btn-lg button" %>
    </form>
  </div>
</div>
<% end %>

rails-base-master/app/views/users/new.html.erb
<%= render 'form', user: @user %>